std_msgs/Header header

uint8 device_id

uint8 health
float32 voltage
float32 current
float32 remaining
uint32 time_remaining
float32 temperature
uint16 cycle_count
float32[] voltages 




uint16 state
uint16 STATUS_FLAG_OK = 0
uint16 STATUS_PRE_ACTIVE = 1
uint16 STATUS_PRE_EVER = 2
uint16 STATUS_POWER_ACTIVE = 3
uint16 STATUS_POWER_INACTIVE = 4
uint16 STATUS_FLAG_CHARGING = 5
uint16 STATUS_FLAG_CHARGED = 6
uint16 STATUS_FLAG_TEMP_HOT = 7
uint16 STATUS_FLAG_TEMP_COLD = 8
uint16 STATUS_FLAG_OVERLOAD = 9
