
uint8 VEHICLE_CODE_AC_ONLINE = 1
uint32 vehicle_code

uint8 UAV_CODE_HANGER_ONLINE = 1
uint32 uav_code

uint8 open
uint8 open_schedule
uint8 close
uint8 close_schedule
uint8[20] error_code
uint8 ChargeState    
uint8 KeyState       
uint8 HotState    
uint8 BeepState       
float32 BattVolt  
float32 BattCurr    
uint8 SOC            
uint16 DischgTime    
uint16 MaxCellVolt 
uint8 MaxCvNO     
uint16 MinCellVolt 
uint8 MinCvNO       
uint8 MaxCellTemp   
uint8 MaxCtNO        
uint8 MinCellTemp  
uint8 MinCtNO        
uint8 AvrgCellTemp   
uint32 AlmInfo     
uint32 param1
uint32 param2
uint32 param3
uint32 param4
uint32 param5
uint32 param6
uint32 param7
uint32 param8