
uint32 device_type
uint32 device_id
string firmware_version
uint16 type
uint32 firmware_git_hash
uint32 hardware_version
string uid
string model

uint16 UAT_DEVICE_FIRMWARE = 7   # 飞控
uint16 UAT_DEVICE_GNSS = 11  # 卫导板
uint16 UAT_DEVICE_LEFT_BATTERY = 20  # 电池1
uint16 UAT_DEVICE_RIGHT_BATTERY = 21  # 电池2
uint16 UAT_DEVICE_VBASEBOARD = 25  # 视觉板
uint16 UAT_DEVICE_M4 = 27  #M4
uint16 UAT_DEVICE_CONVERTERBOARD = 50  # 云台
uint16 UAT_DEVICE_ESC_1 = 241 # 电调1
uint16 UAT_DEVICE_ESC_2 = 242  # 电调2
uint16 UAT_DEVICE_ESC_3 = 243  # 电调3
uint16 UAT_DEVICE_ESC_4 = 244  # 电调4
uint16 UAT_DEVICE_NODEID_OFFBOARD = 2  # NX
uint16 UAT_DEVICE_MSG_CODE = 60  # msg code

