uint8 CMD_TYPE_SET_MOUNT_MODE = 1
uint8 MOUNT_MODE_FIX_YAW = 1
uint8 MOUNT_MODE_FOLLOW_YAW = 2

uint8 CMD_TYPE_CTL_MOUNT_ATTITUDE = 2

uint8 CMD_TYPE_CTL_MOUNT_RATE = 3

uint8 CMD_TYPE_CAPTURE_CONTROL = 4

uint8 CMD_TYPE_VEDIO_CONTROL = 5

uint8 CMD_TYPE_CAMERA_ZOOM = 6

uint8 CMD_TYPE_IMAGE_SWITCH = 7
uint8 STREAM_TYPE_VISIBLE_ONLY = 0
uint8 STREAM_TYPE_IR_ONLY = 1
uint8 STREAM_TYPE_IR_IN_VISIBLE = 2
uint8 STREAM_TYPE_VISIBLE_IN_IR = 3
uint8 STREAM_TYPE_VISIBLE_WITH_IR = 4

uint8 CMD_TYPE_CONTROL_POINT = 8
uint8 CTL_POINT_MODE_MOVE = 1
uint8 CTL_POINT_MODE_FOCUS = 2
uint8 CTL_POINT_MODE_TRACKING = 3
uint8 CTL_POINT_MODE_GET_TEMPERATURE = 4

uint8 CMD_TYPE_AIREC_TRACK_CONTROL = 9
uint8 AITRACK_SOURCE_VISIBLE = 1
uint8 AITRACK_SOURCE_IR = 2

uint8 CMD_TYPE_RECOGNIZE_CONTROL = 11
uint8 CMD_TYPE_CAMERA_TEMPERATURE = 12
uint8 CMD_TYPE_GET_TRIGGER_STATE = 13

uint32 devid
uint8 cmd 
int32 param1
int32 param2
int32 param3
float32 param4
float32 param5
float32 param6
float32 param7

---
bool ok
uint8 res_cmd
int32 param1
int32 param2
int32 param3
float32 param4
float32 param5
float32 param6
float32 param7