uint8 GCS_CTRL = 1
uint8 CLOUD_SERVER = 2
uint8 source


#   Frame ID = 0x02,Message ID = 0x01
#   param1 expand action
#   Frame ID = 0x02,Message ID = 0x02
#   param1  close operation

uint8 frame_id
uint8 message_id
uint8 param1
uint8 param2
uint8 param3
uint8 param4
uint8 param5
uint8 param6
uint8 param7
uint8 param8

---
bool ok
uint8 source
uint8 frame_id
uint8 message_id
uint8 param1
uint8 param2
uint8 param3
uint8 param4
uint8 param5
uint8 param6
uint8 param7
uint8 param8